### ISSUE TITLE
remove Yii2 dependencies from package

### ISSUE THREAD

**Issue by strorch** [hiqdev/php-data-mapper#3]
Suggestion to move classes with Yii2 dependencies and their Yii2-DI configurations to https://github.com/hiqdev/yii2-data-mapper

For example:
 - Move validator classes
 - Move config/common.php and config/params.php
 - In hiqdev\DataMapper\Attribution\Bucket use Yiisoft\Arrays\ArrayHelper instead of yii\helpers\ArrayHelper
 - https://github.com/hiqdev/php-data-mapper/pull/2

and etc.

**Comment by SilverFire** [comment]
Done
